resources:
  - name: myApplication
    type: RemoteFile
    configuration:
      sourceArtifactory: Artifactory
      fileLocation: generic-generic-local
  - name: myVM
    type: VmCluster
    configuration:
      sshKey: mySSHKey
      targets:
        - 0.0.0.0
        - 1.1.1.1
pipelines:
  - name: linuxVMDeployPipeline
    steps:
      - name: linuxVMDeploy
        type: LinuxVMDeploy
        configuration:
          inputResources:
            - name: myVM
            - name: myApplication
          scripts:
            - name: deployCommand
              context: targetCluster
              commands:
                - "bash vraj.sh"
