resources:
  - name: RemoteFile_2
    type: RemoteFile
    configuration:
      source: Artifactory
      fileLocation: deploy-generic-local # name of the artifactory from which one need to deploy the file
     
pipelines:
  - name: Production_pipelines_file # Name of pipeline
    steps:
      - name: REFILE_1
        type: bash
        configuration:
          inputResources:
            - name: RemoteFile_2
          nodePool: final # Name of node pool
          integrations:
            - name: Artifactory
          outputResources:
            - name: RemoteFile_2
        execution:
          onExecute:
            - echo "executing step..."
            - bash vraj.sh
            - jfrog rt dl deploy-generic-local --sort-by=created --sort-order=desc --limit=1
